name: Main Workflow
on:
  workflow_dispatch:
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    ## Run K6 Test
      - name: Run k6 local test
        uses: far11ven/xk6-action@0.0.2
        with:
          filename: code/scripts/script.js