name: Main Workflow
on:
  workflow_dispatch:
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    ## Run K6 Test
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: code/scripts/script.js